### ISSUE TITLE
Request to participate Hactoberfest

### ISSUE THREAD

**Issue by L0SER8228** [YT-GameWorks/Cent-Utilities-Bot#8]
I think it will be great if you participate on hactoberfest. More people will come to contribute. Please make this repo available for hactoberfest participate.🙏

**Comment by YT-GameWorks** [comment]
Hi, I just started making bots and I really don't know what hactoberfest is ! I will see after I get home !

**Comment by Aktindo** [comment]
Hi! Yes sure we will in some time!
